# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rust_reverse.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"

gem "minitest", "~> 5.0"

gem "standard", "~> 1.3"
