# frozen_string_literal: true

require "rake/testtask"
require "rake/extensiontask"
require "rb_sys/toolchain_info"

SOURCE_PATTERN = "*.{rs,toml,lock,rb}"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/test_*.rb"]
end

Rake::ExtensionTask.new("rust_reverse") do |ext|
  ext.lib_dir = "lib/rust_reverse"
  ext.source_pattern = SOURCE_PATTERN
  ext.cross_compile = true
  ext.cross_platform = RbSys::ToolchainInfo.supported_ruby_platforms
  ext.config_script = ENV["ALTERNATE_CONFIG_SCRIPT"] || "extconf.rb"
end

task :build do
  require "bundler"

  spec = Bundler.load_gemspec("rust_reverse.gemspec")

  FileUtils.rm_rf("pkg/rust_reverse")

  spec.files.each do |file|
    FileUtils.mkdir_p("pkg/rust_reverse/#{File.dirname(file)}")
    FileUtils.cp(file, "pkg/rust_reverse/#{file}")
  end

  FileUtils.cp("rust_reverse.gemspec", "pkg/rust_reverse")

  full_path = File.expand_path("./../../../crates/rb-sys", __FILE__)
  cargo_toml_path = "pkg/rust_reverse/ext/rust_reverse/Cargo.toml"
  new_contents = File.read(cargo_toml_path).gsub("./../../../../crates/rb-sys", full_path)
  FileUtils.rm(cargo_toml_path)
  File.write(cargo_toml_path, new_contents)

  Dir.chdir("pkg/rust_reverse") do
    sh "gem build rust_reverse.gemspec --output=../rust_reverse.gem"
  end
end

task default: %i[compile test]
