# frozen_string_literal: true

require "rake/testtask"
require_relative "rake_ext"
require "rake/javaextensiontask"
require "rake/extensiontask"

SOURCE_PATTERN = "*.{rs,toml,lock,rb}"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/test_*.rb"]
end

Rake::JavaExtensionTask.new("rust_reverse") do |ext|
  ext.lib_dir = "lib/rust_reverse"
  ext.ext_dir = "ext"
  ext.source_version = "11"
  ext.target_version = "11"
end

Rake::Task[:compile].rename(:java_compile)

Rake::ExtensionTask.new("rust_reverse") do |ext|
  ext.lib_dir = "lib/rust_reverse"
  ext.source_pattern = SOURCE_PATTERN
  ext.cross_compile = true
  ext.cross_platform = %w[x86-mingw32 x64-mingw-ucrt x64-mingw32 x86-linux x86_64-linux x86_64-darwin arm64-darwin aarch64-linux]
  ext.config_script = ENV["ALTERNATE_CONFIG_SCRIPT"] || "extconf.rb"
end

task compile: :java_compile

task :build do
  require "bundler"

  spec = Bundler.load_gemspec("rust_reverse.gemspec")

  FileUtils.rm_rf("pkg/rust_reverse")

  spec.files.each do |file|
    FileUtils.mkdir_p("pkg/rust_reverse/#{File.dirname(file)}")
    FileUtils.cp(file, "pkg/rust_reverse/#{file}")
  end

  FileUtils.cp("rust_reverse.gemspec", "pkg/rust_reverse")

  full_path = File.expand_path("./../../../crates/rb-sys", __FILE__)
  cargo_toml_path = "pkg/rust_reverse/ext/rust_reverse/Cargo.toml"
  new_contents = File.read(cargo_toml_path).gsub("./../../../../crates/rb-sys", full_path)
  FileUtils.rm(cargo_toml_path)
  File.write(cargo_toml_path, new_contents)

  Dir.chdir("pkg/rust_reverse") do
    sh "gem build rust_reverse.gemspec --output=../rust_reverse.gem"
  end
end

task default: %i[compile test]
