//! Raw bindings to libruby, generated by bindgen.
//!
//! This module contains the raw bindings to libruby, generated by bindgen.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unknown_lints)]
#![allow(deref_nullptr)]
#![warn(unknown_lints)]
#![allow(unaligned_references)]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
