name: Documentation Tests

on:
  push:
    branches: [main, doctest-stabilize]
    paths:
      - "docsite/docs/**/*.mdx"
      - "docsite/docs/**/*.md"
      - ".github/workflows/doctest.yml"
  pull_request:
    paths:
      - "docsite/docs/**/*.mdx"
      - "docsite/docs/**/*.md"
      - ".github/workflows/doctest.yml"

jobs:
  doctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          rustup-toolchain: stable
          rustup-components: clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run doctests
        run: bundle exec rake doctest:run

      - name: Build docs
        run: bundle exec rake docsite:build

      - name: Check for broken links
        run: |
          cd docsite
          # Install markdown-link-check
          npm install -g markdown-link-check

          # Check all markdown files
          find docs -name "*.md" -o -name "*.mdx" | xargs -I {} markdown-link-check {} || true
